ServiceCourse/ServiceCourse.Web/Models/CourseViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ServiceCourse.Web.Models
{
    public class CourseViewModel
    {
        public int CourseId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public double Price { get; set; }
        public EnrollmentStatus Status { get; set; }
        public string CoverImg { get; set; }
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }

        public enum EnrollmentStatus
        {
            [Display(Name = "Abertas")]
            Abertas = 1,

            [Display(Name = "Fechadas")]
            Fechadas = 2
        }
    }
}

ServiceCourse/ServiceCourse.Web/Models/LoginViewModel.cs
namespace ServiceCourse.Web.Models
{
    public class LoginViewModel
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
    }
}

ServiceCourse/ServiceCourse.Web/Controllers/CourseController.cs
using ServiceCourse.Domain.Models;
using ServiceCourse.Domain.Services;
using ServiceCourse.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ServiceCourse.Web.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        CourseService _courseService = new CourseService();
        TeacherService _teacherService = new TeacherService();

        public ActionResult Index()
        {
            var courses = _courseService.GetCourses();
            var coursesViewModel = new List<CourseViewModel>();

            foreach (var course in courses)
            {
                coursesViewModel.Add(new CourseViewModel
                {
                    CourseId = course.CourseId,
                    Name = course.Name,
                    Description = course.Description,
                    Duration = course.Duration,
                    CoverImg = course.CoverImg,
                    TeacherId = course.TeacherId,
                    Price = course.Price,
                    Status = (CourseViewModel.EnrollmentStatus)course.Status
                });
            }
            if (courses.Count == 0 || courses == null)
            {
                ViewBag.Message = "Não existem cursos cadastrados.";
            }
            return View(coursesViewModel);
        }

        public ActionResult Details(int id)
        {
            var course = _courseService.GetCourseById(id);

            var teacher = _teacherService.GetTeacherById(course.TeacherId);

            if (teacher != null)
                course.TeacherName = teacher.TeacherName;

            var courseViewModel = new CourseViewModel()
            {
                CourseId = course.CourseId,
                Name = course.Name,
                Description = course.Description,
                Duration = course.Duration,
                Price = course.Price,
                CoverImg = course.CoverImg,
                TeacherId = course.TeacherId,
                TeacherName = course.TeacherName,
                Status = (CourseViewModel.EnrollmentStatus)course.Status
            };

            return View(courseViewModel);
        }

        public ActionResult Create()
        {
            var teachers = _teacherService.GetTeachers();

            ViewBag.Teachers = new SelectList(teachers, "Id", "TeacherName");

            return View();
        }

        [HttpPost]
        public ActionResult Create(CourseViewModel courseViewModel)
        {
            try
            {
                CourseModel course = new CourseModel()
                {
                    Name = courseViewModel.Name,
                    Description = courseViewModel.Description,
                    Duration = courseViewModel.Duration,
                    TeacherId = courseViewModel.TeacherId,
                    CoverImg = courseViewModel.CoverImg,
                    Price = courseViewModel.Price,
                };

                _courseService.CreateCourse(course);

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = ex.Message });
            }
        }

        public ActionResult Edit(int id)
        {
            var course = _courseService.GetCourseById(id);
            var teachers = _teacherService.GetTeachers();

            var selectedTeacher = teachers.FirstOrDefault(p => p.Id == course.TeacherId);
            if (selectedTeacher != null)
            {
                teachers.Insert(0, selectedTeacher);
            }
            else
            {
                teachers.Insert(0, new TeacherModel { Id = 0, TeacherName = "Selecione um professor" });
            }

            ViewBag.Teachers = new SelectList(teachers.Distinct(), "Id", "TeacherName");

            var courseViewModel = new CourseViewModel()
            {
                CourseId = course.CourseId,
                Name = course.Name,
                Description = course.Description,
                Duration = course.Duration,
                TeacherId = course.TeacherId,
                CoverImg = course.CoverImg,
                Price = course.Price,
                Status = (CourseViewModel.EnrollmentStatus)course.Status
            };

            return View(courseViewModel);
        }

        [HttpPost]
        public ActionResult Edit(CourseViewModel courseViewModel)
        {
            try
            {
                CourseModel course = new CourseModel()
                {
                    CourseId = courseViewModel.CourseId,
                    Name = courseViewModel.Name,
                    Description = courseViewModel.Description,
                    Duration = courseViewModel.Duration,
                    TeacherId = courseViewModel.TeacherId,
                    CoverImg = courseViewModel.CoverImg,
                    Price = courseViewModel.Price,
                    Status = (CourseModel.EnrollmentStatus)courseViewModel.Status
                };

                _courseService.UpdateCourse(course);

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = ex.Message });
            }
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                _courseService.DeleteCourse(id);
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = ex.Message });
            }
        }
    }
}

ServiceCourse/ServiceCourse.Web/Controllers/LessonController.cs
using ServiceCourse.Domain.Models;
using ServiceCourse.Domain.Services;
using ServiceCourse.Web.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ServiceCourse.Web.Controllers
{
    [Authorize]
    public class LessonController : Controller
    {
        LessonService service = new LessonService();

        public ActionResult Index(int id)
        {
            ViewBag.CourseId = id;

            var lessons = service.GetLessonsByCourseId(id);
            var lessonsViewModel = new List<LessonViewModel>();

            foreach (var lesson in lessons)
            {
                lessonsViewModel.Add(new LessonViewModel
                {
                    LessonId = lesson.LessonId,
                    CourseId = lesson.CourseId,
                    Name = lesson.Name,
                    Description = lesson.Description,
                    LessonUrl = lesson.LessonUrl,
                    Image = lesson.Image,
                });
            }
            if (lessons.Count == 0 || lessons == null)
            {
                ViewBag.Message = "Não existem lições cadastradas.";
            }
            return View(lessonsViewModel);
        }

        public ActionResult Details(int id)
        {
            var lesson = service.GetLessonById(id);

            var lessonViewModel = new LessonViewModel()
            {
                LessonId = lesson.LessonId,
                CourseId = lesson.CourseId,
                Name = lesson.Name,
                Description = lesson.Description,
                LessonUrl = lesson.LessonUrl,
                Image = lesson.Image,
            };

            return View(lessonViewModel);
        }

        public ActionResult Create(int id)
        {
            ViewBag.CourseId = id;

            return View();
        }

        [HttpPost]
        public ActionResult Create(LessonViewModel lessonViewModel)
        {
            try
            {
                LessonModel lesson = new LessonModel()
                {
                    Name = lessonViewModel.Name,
                    CourseId = lessonViewModel.CourseId,
                    Description = lessonViewModel.Description,
                    LessonUrl = lessonViewModel.LessonUrl,
                    Image = lessonViewModel.Image,
                };

                service.CreateLesson(lesson);

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = ex.Message });
            }
        }

        public ActionResult Edit(int id)
        {
            var lesson = service.GetLessonById(id);

            var lessonViewModel = new LessonViewModel()
            {
                LessonId = lesson.LessonId,
                CourseId = lesson.CourseId,
                Name = lesson.Name,
                Description = lesson.Description,
                LessonUrl = lesson.LessonUrl,
                Image = lesson.Image,
            };

            ViewBag.CourseId = lessonViewModel.CourseId;

            return View(lessonViewModel);
        }

        [HttpPost]
        public ActionResult Edit(LessonViewModel lessonViewModel)
        {
            try
            {
                LessonModel lesson = new LessonModel()
                {
                    LessonId = lessonViewModel.LessonId,
                    CourseId = lessonViewModel.CourseId,
                    Name = lessonViewModel.Name,
                    Description = lessonViewModel.Description,
                    LessonUrl = lessonViewModel.LessonUrl,
                    Image = lessonViewModel.Image,
                };

                service.UpdateLesson(lesson);

                return Json(new { success = true });

            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = ex.Message });

            }
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                service.DeleteLesson(id);
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, errorMessage = ex.Message });
            }
        }
    }
}

ServiceCourse/ServiceCourse.Web/Controllers/LoginController.cs
using ServiceCourse.Domain.Services;
using ServiceCourse.Web.Models;
using System.Web.Mvc;
using System.Web.Security;

namespace ServiceCourse.Web.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        LoginService service = new LoginService();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel login)
        {
            var user = service.GetuserByEmail(login.Email, login.Password);
            var authenticate = service.Authenticate(login.Password, user.Password, user.Salt);

            if (authenticate)
            {
                FormsAuthentication.RedirectFromLoginPage(login.Email, createPersistentCookie: false);
                return RedirectToAction("Index", "Home");

            }
            else
            {
                ViewBag.ErrorMessage = "Credenciais inválidas. Tente novamente.";
                return View();

            }

        }
    }
}

ServiceCourse/ServiceCourse.Web/Views/Course/Create.cshtml
@model ServiceCourse.Web.Models.CourseViewModel

@{
    ViewBag.Title = "Create";
}


<div class="form-horizontal">
    <form id="createForm">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Nome</label>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control form-control-user", @placeholder = "Nome" } })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Descrição</label>
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-user", @placeholder = "Descrição" } })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Imagem de capa</label>
                @Html.EditorFor(model => model.CoverImg, new { htmlAttributes = new { @class = "form-control form-control-user", @placeholder = "Capa" } })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Duração</label>
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control form-control-user", @placeholder = "Duração" } })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Professor</label>
                @Html.DropDownListFor(model => model.TeacherId, ViewBag.Teachers as SelectList, "Selecione um professor", new { @class = "form-control", @placeholder = "Professor" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Preço</label>
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control form-control-user", @placeholder = "Preço" } })
            </div>
        </div>
        <div class="form-group">
            <button type="submit" value="Create" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" id="btnSubmit">
                <i class="fas fa-download fa-sm text-white-50"></i>
                Salvar
            </button>
        </div>
    </form>

</div>

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function createCourse() {
          $('#createForm').submit(function(e) {
              e.preventDefault();

              var priceInput = $('#Price');
              var price = parseFloat(priceInput.val().replace(',', '.'));

              if (validateForm()) {

                  var formData =
                  {
                      Name: $('#Name').val(),
                      Description: $('#Description').val(),
                      Duration: $('#Duration').val(),
                      TeacherId: $('#TeacherId').val(),
                      CoverImg: $('#CoverImg').val(),
                      Price: price
                  };

                  var jsonData = JSON.stringify(formData);

              $.ajax({
                type: 'POST',
                url: '@Url.Action("Create", "Course")',
                  data: jsonData,
                  contentType: 'application/json',

                  success: function (result) {
                      if (result.success) {
                           window.location.href = '@Url.Action("Index", "Course")';
                      }
                },
                error: function(xhr, status, error) {
                    alert('Ocorreu um erro ao criar o registro: ' + result.errorMessage);
                }
              });
            }
          });
    };

    function isValidNumber(value) {
        return !isNaN(parseFloat(value)) && isFinite(value);
    }

    function validateForm() {
        var isValid = true;

        $('input[type="text"], input[type="number"]').each(function () {
            if ($.trim($(this).val()) === '') {
                isValid = false;
                $(this).addClass('border-danger');
            } else {
                $(this).removeClass('border-danger');
            }
        });


        return isValid;
    }

    $(document).ready(function () {
        createCourse();
    });


    </script>
}

ServiceCourse/ServiceCourse.Web/Views/Course/Details.cshtml
@model ServiceCourse.Web.Models.CourseViewModel

@{
    ViewBag.Title = "Details";
}

<a href="@Url.Action("Index", "Lesson")" class="btn btn-primary btn-sm" style="float: right; display: flex; margin-top: 10px">
    Aulas
</a>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nome
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Descrição
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            Professor
        </dt>

        <dd>
            @if (Model.TeacherName is null)
            {
                <p>Nenhum professor cadastrado</p>
            }
            else
            {
                @Html.DisplayFor(model => model.TeacherName)

            }
        </dd>
        <dt>
            Duração
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration) meses
        </dd>

        <dt>
            Preço
        </dt>

        <dd>
            R$@Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            Status
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            Imagem de capa
        </dt>
        <dd>
            @if (Model.CoverImg is null)
            {
                <p>Nenhuma imagem cadastrada</p>
            }
            else
            {
                <div class="col-sm-6">
                    <img id="imgPreview" src="@Html.DisplayFor(model => model.CoverImg)" alt="Pré-visualização da Imagem" class="img-fluid" style="max-height: 200px; max-width: 200px;" />
                </div>
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.CourseId }) |
    @Html.ActionLink("Voltar", "Index")
</p>

ServiceCourse/ServiceCourse.Web/Views/Course/Edit.cshtml
@model ServiceCourse.Web.Models.CourseViewModel

@{
    ViewBag.Title = "Edit";
}


<div class="form-horizontal">
    <form id="editForm">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CourseId)

        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Nome</label>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome" } })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Descrição</label>
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Descrição" } })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Imagem de capa</label>
                @Html.EditorFor(model => model.CoverImg, new { htmlAttributes = new { @class = "form-control form-control-user", @placeholder = "Capa" } })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Duração</label>
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", @placeholder = "Duração" } })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Professor</label>
                @Html.DropDownListFor(model => model.TeacherId, ViewBag.Teachers as SelectList, "Selecione um professor", new { @class = "form-control", @placeholder = "Professor" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Preço</label>
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @placeholder = "Preço" } })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <label for="Name">Status</label>
                @Html.DropDownListFor(model => model.Status, new SelectList(Enum.GetValues(typeof(ServiceCourse.Web.Models.CourseViewModel.EnrollmentStatus))), new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <button type="submit" value="Edit" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-download fa-sm text-white-50"></i>
                Salvar
            </button>
        </div>
    </form>
</div>


<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function validateForm() {
            var isValid = true;

            $('input[type="text"], input[type="number"]').each(function () {
                if ($.trim($(this).val()) === '') {
                    isValid = false;
                    $(this).addClass('border-danger');
                } else {
                    $(this).removeClass('border-danger');
                }
            });
            var priceInput = $('#Price');
            var priceValue = parseFloat(priceInput.val().replace(',', '.'));

            if (isNaN(priceValue)) {
                priceInput.addClass('border-danger');
                isValid = false;
            } else {
                priceInput.removeClass('border-danger');
            }

            if (!isValid) {
                alert('Por favor, preencha todos os campos obrigatórios e verifique o campo "Preço".');
            }

            return isValid;
    };
    function editForm() {
         $('#editForm').submit(function (e) {
             e.preventDefault();
            if (validateForm()) {
                var priceInput = $('#Price');
                var price = parseFloat(priceInput.val().replace(',', '.'));

                var formData = {
                    CourseId: $('#CourseId').val(),
                    Name: $('#Name').val(),
                    Description: $('#Description').val(),
                    Duration: $('#Duration').val(),
                    TeacherId: $('#TeacherId').val(),
                    CoverImg: $('#CoverImg').val(),
                    Price: price,
                    Status: $('#Status').val()
                };
                var jsonData = JSON.stringify(formData);

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Edit", "Course", new { id = Model.CourseId })',
                    data: jsonData,
                    contentType: 'application/json',
                    success: function (result) {
                        if (result.success) {
                             window.location.href = '@Url.Action("Index", "Course")';
                        }
                    },
                    error: function (xhr, status, error) {
                        alert('Ocorreu um erro ao editar o registro: ' + errorMessage);
                    }
                });
             }
         });
    }
    $(document).ready(function () {
        editForm();
    });
    </script>
}

ServiceCourse/ServiceCourse.Web/Views/Course/Index.cshtml
@model IEnumerable<ServiceCourse.Web.Models.CourseViewModel>


@{
    ViewBag.Title = "List";
}


<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="@Url.Action("Create", "Course")" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i>
        Novo curso
    </a>
</div>

<div class="table-responsive">
    @if (ViewBag.Message != null)
    {
        <p>@ViewBag.Message</p>
    }
    else
    {
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Nome
                </th>
                <th>
                    Descrição
                </th>
                <th>
                    Duração
                </th>
                <th>
                    Preço
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CourseId)
                    </td>
                    <th>
                        @Html.DisplayFor(modelItem => item.Name)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duration) meses
                    </td>
                    <td>
                       R$@Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Course", new { id = item.CourseId })"class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                            <i class="fas fa-download fa-sm text-white-50"></i>
                            Editar
                        </a>
                        <a href="@Url.Action("Details", "Course", new { id = item.CourseId })" class="d-none d-sm-inline-block btn btn-sm btn-info shadow-sm">
                            <i class="fas fa-download fa-sm text-white-50"></i>
                            Detalhes
                        </a>
                        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm delete-link" data-course-id="@item.CourseId" data-delete-url="@Url.Action("Delete", "Course", new { id = item.CourseId })">
                            <i class="fas fa-download fa-sm text-white-50"></i>
                            Excluir
                        </a>
                        <div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirmação de Exclusão</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Tem certeza que deseja excluir este item?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <button type="button" class="btn btn-danger" id="confirmDeleteButton" >Confirmar Exclusão</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>
                </tr>
            }

        </table>
    }

</div>



@Scripts.Render("~/course")

ServiceCourse/ServiceCourse.Web/Views/Course/Login.cshtml
@model ServiceCourse.Web.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "Course", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.Login, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Login, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Login" class="btn btn-default" />
        </div>
    </div>
}